imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: database.yml }
    - { resource: sonata.yml }
    - { resource: "@AppSiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    option_locales: [da, no, sv, fi, fr, en]
    front_campaign_ids: [147, 148]
    supported_countries:
      da:
        name: 'Danish'
        locale: 'da'
        country_code: 'DK'
        flag: 'dk'
        currency: 'DKK'
        phone_prefix: '+45'
        phone_length_min: '8'
        phone_length_max: '8'
        enabled: 1
      en:
        name: 'English'
        locale: 'en'
        country_code: 'EN'
        flag: 'gb'
        currency: 'EUR'
        phone_prefix: '+'
        phone_length_min: '1'
        phone_length_max: '30'
        enabled: 1
      no:
        name: 'Norwegian'
        locale: 'no'
        country_code: 'NO'
        flag: 'no'
        currency: 'NOK'
        phone_prefix: '+47'
        phone_length_min: '8'
        phone_length_max: '8'
        enabled: 0
      sv:
        name: 'Swedish'
        locale: 'sv'
        country_code: 'SE'
        flag: 'se'
        currency: 'SEK'
        phone_prefix: '+46'
        phone_length_min: '7'
        phone_length_max: '9'
        enabled: 0
    subscription_roles:
      basic: ROLE_BASIC
      pro: ROLE_PRO

framework:
    #esi:             ~
    translator: { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        cookie_secure: true
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ FOSUserBundle, SonataAdminBundle, AppSiteBundle ]
    sass:  "%sass_location%"
    ruby:  "%ruby_location%"
    filters:
        cssrewrite: ~
        compass:
            bin: "%compass_location%"
        sass:
            bin: "%sass_location%"
            apply_to: '\.scss$'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider:        "@security.csrf.token_manager"
        supported_countries:      "%supported_countries%"
        app_name:                 "%app_name%"
        app_domain:               "%app_domain%"
        support_email:            "%support_email%"

        option_locales:           "%option_locales%"

        support_phone:            "+45 88 82 03 64"
        tech_phone:               "+45 88 82 03 64"
        phone_time:               "10:00 - 15:00"

        company_name:             "MP Software Group"
        company_cvr:              "38784471"
        company_address:          "ET Jørgensens Vej 5, 1. tv."
        company_city:             "7100 Vejle"
        company_country:          "Denmark"

        domain_name:              "EasyWebBuilder.eu"
        domain_url:               "https://easywebbuilder.eu"

        shipping_from_company:    "EasyWebBuilder"
        shipping_from_country:    "DK"
        shipping_from_city:       "XX"
        shipping_from_zipcode:    "XXXX"
        shipping_from_address:    "XXXXXXXXX"

        product_1: "https://buy.easywebbuilder.eu/en/c/easywebbuilder"
        product_2: "https://buy.easywebbuilder.eu/en/c/easywebbuilder-pro"

        facebook_profile: "https://www.facebook.com/MP-Software-Group-IVS-165016410733447/"
        twitter_profile: "https://twitter.com/MPGroup_EasyWeb"
        linkedin_profile: "https://www.linkedin.com/company-beta/11232582/"
        pinterest_profile: "https://www.pinterest.com/easywebbuilder0041/"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Shop\UserBundle\Entity\User
    from_email:
        address:        "contact@easywebbuilder.eu"
        sender_name:    "EasyWebBuilder"
    service:
        mailer: user_mailer

fos_rest:
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    disable_csrf_role: ROLE_API_PUBLIC
    view:
        view_response_listener: true

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


uecode_api_key:
    delivery: query
    parameter_name: apikey


jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: ['SonataAdminBundle', 'routes']
            excluded_names: ["*TestCase.php", "*Test.php", "*Admin.php"]
            excluded_dirs: [cache, data, logs, Features]
            extractors: [jms_i18n_routing]

jms_i18n_routing:
    default_locale: %locale%
    locales: %option_locales%
    strategy: prefix_except_default

fos_rest:
    param_fetcher_listener: force
    routing_loader:
        default_format: json
    disable_csrf_role: ROLE_CUSTOMER
    view:
        view_response_listener: true
    serializer:
        serialize_null: true
