security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_API_PUBLIC:              [ROLE_API_PUBLIC]
        ROLE_API_SECRET:              [ROLE_API_SECRET]
        ROLE_CUSTOMER:                [ROLE_USER, ROLE_CUSTOMER]

        ROLE_BASIC:                   [ROLE_CUSTOMER, ROLE_BASIC]
        ROLE_PRO:                     [ROLE_BASIC, ROLE_PRO]
        ROLE_LIFETIME:                [ROLE_PRO, ROLE_LIFETIME]

        ROLE_ADMIN:                   [ROLE_LIFETIME, ROLE_SONATA_ADMIN, ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        apikey:
            id: uecode.api_key.provider.user_provider

    firewalls:
        stateless:
            pattern: ^/api/s/
            anonymous: true
            api_key: true
            stateless: true
            provider: apikey
        main:
            pattern: ^/
            simple_form:
                provider: fos_userbundle
                authenticator: user_authenticator
                login_path: homepage
                check_path: fos_user_security_check
                default_target_path: light_builder_my_sites
            logout:
                path: fos_user_security_logout
                target: /
            anonymous: true

    access_control:
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }         # allow wdt for debugging
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }    # allow profiler for debugging
        - { path: ^/bundles/, role: IS_AUTHENTICATED_ANONYMOUSLY }      # allow assets to be loaded anonymously
        - { path: "^/user/login$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/user/login/token$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/user/profile", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/user/register", role: ROLE_ADMIN }
        - { path: "^/user/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/user/", role: ROLE_CUSTOMER }
        - { path: "^/light-builder/", role: ROLE_CUSTOMER }
        - { path: "^/advanced-builder/", role: ROLE_CUSTOMER }
        - { path: "^/admin/", role: ROLE_ADMIN }
