# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    sonata.admin.job:
        class: App\CoreBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Jobs", label: "Jobs" }
        arguments:
            - ~
            - App\CoreBundle\Entity\Job
            - ~
        calls:
            - [ setTranslationDomain, [AppCoreBundleJob]]
            - [ setContainer,[ "@service_container" ] ]