services:
    notification_manager:
        class: App\NotificationBundle\Manager\NotificationManager
        arguments: []
        calls:
            - [ setContainer,[ "@service_container" ] ]

    notification.action_listener:
        class: App\NotificationBundle\EventListener\NotificationListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
